### ISSUE TITLE
Semantic segmetation ;common settings  MMSegmentation link not working

### ISSUE THREAD

**Issue by 100daggers** [SysCV/bdd100k-models#10]
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/model_zoo.md#common-settings
The above link is not working

I would like to know the settings under which the segmentation models are trained , so that i can replicate the results .
thank you.

**Comment by thomasehuang** [comment]
Here is the updated link: https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/model_zoo.md#common-settings
