### ISSUE TITLE
Using the models to predict on other Images

### ISSUE THREAD

**Issue by askppp** [SysCV/bdd100k-models#13]
Hi,

can i use the models under "bdd100k-models/det/" to make predictions on other images ?

When i followed the "Usage"-Section, it seems that the models can only be used to evaluate the Test/Val Images.

**Comment by sunny0414** [comment]
@askppp I also want to do this,but don't have the predict script.

**Comment by thomasehuang** [comment]
Hello, you can try using this script in MMDetection: https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py. Let me know if there are any further difficulties with this.

**Comment by askppp** [comment]
Hi again,
thanks, it worked. 
@sunny0414 you have to download the script and then you can run like this:

python image_demo.py Path_Image_File Path_Config_File Path_Checkpoint_File(.pth)

Change the Paths according to your folders.

**Comment by pupu-chenyanyan** [comment]
@askppp oh yes,thanks you.

**Comment by thomasehuang** [comment]
@askppp Thanks for the help! I will update the READMEs sometime to add this.
