### ISSUE TITLE
Generate semantic segmentation output as png 

### ISSUE THREAD

**Issue by digvijayad** [SysCV/bdd100k-models#17]
Hello,

I'm generating semantic segmentation using the following command. 
```
python ./test.py ~/config.py --show-dir ~/Documents/bdd100k-models/data/bdd100k/labels/seg_track_20/val --opacity 1
```
This generates the colormaps for the images, however, the output produced is in .jpg format which results in blur within the labels (as shown below.) How can I update the script so that it generates the labels in png format.  My input images are from the `MOTS 2020 Images` dataset, which are in jpg format. 

![image](https://user-images.githubusercontent.com/19765483/179498684-40dd345d-20f2-458c-8b5f-2a2a0e39a0db.png)

**Comment by thomasehuang** [comment]
You may have to modify the mmsegmentation inference code to modify the saving of the images (see https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/apis/test.py). Or you can copy the function over to `./test.py` and modify it there.

**Comment by digvijayad** [comment]
Thanks, I modified the BDD100KSemSegDataset's `format_results` function based on the the [cityscapes](https://mmsegmentation.readthedocs.io/en/latest/_modules/mmseg/datasets/cityscapes.html) CustomDataset definition.
