### ISSUE TITLE
mmcv>=2.0.0 compatibility

### ISSUE THREAD

**Issue by d4l3k** [SysCV/bdd100k-models#21]
With the new mmcv 2.0.0 there's a lot of backward compatibility breaking changes. It seems like mmcls doesn't exist and has been renamed mmpretrain so all of the mmcls based configs won't load in this repo now.

```
        f'Please install mmcv>={mmcv_minimum_version}, <={mmcv_maximum_version}.'
E   AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.4.2, <=1.9.0.
```

**Comment by thomasehuang** [comment]
It will take some time for me to update everything to mmcv 2.0.0, so for now you can just install an earlier version of mmcv.

**Comment by d4l3k** [comment]
@thomasehuang the upgrade to mmcv seems pretty challenging. One approach I took was to export one of the models as TorchScript so mmcv wasn't required anymore

https://github.com/d4l3k/torchdrive/commit/4adcc18a72b98ea8c3bbd22c371b317bf0d693d0

I'm not a big fan of mmcv and it'd be great if most models were supported out of the box with a torchscript link. Doesn't seem like it's possible for the mmdet models though

btw, this project has been a huge help so thank you so much!

**Comment by thomasehuang** [comment]
Thanks a lot for the suggestion! Indeed, it will be easier for users if the reliance on MMCV is removed. We will consider this for the future.
