### ISSUE TITLE
Please tell mmcv/mmcv-full version numbers for pose estimation?

### ISSUE THREAD

**Issue by ucalyptus2** [SysCV/bdd100k-models#23]
I have been tearing my hair in trying to run the pose estimation because of version errors:

for your case, what was the mmcv and mmcv-full version that u used because the latest version don't work.

@d4l3k

**Comment by ucalyptus2** [comment]
@thomasehuang

**Comment by d4l3k** [comment]
You can see what works for me at https://github.com/d4l3k/torchdrive/blob/main/requirements.txt


https://github.com/d4l3k/torchdrive/blob/main/Dockerfile.cpu#L8

**Comment by thomasehuang** [comment]
MMCV was recently refactored, so it is not completely compatible anymore. You can get around this by installing an older version `mmcv < 2.0` (instructions [here](https://github.com/open-mmlab/mmcv/releases/tag/v2.0.0)). For your reference, the versions I'm using are `mmcv-full==1.5.0` and `mmpose==0.18.0`. I will make the upgrade to `mmcv>=2.0` so it will be compatible with future versions, but that will take some time. For now, I'll update the installation instructions to avoid version issues with the current version.

Thanks @d4l3k for helping out!
