### ISSUE TITLE
How to obtain the performance of the test set?

### ISSUE THREAD

**Issue by FelixYHH** [SysCV/bdd100k-models#27]
Is there any update on the path for the semantic segmentation task to get test set performance? The link given so far seems to be dead!

**Comment by thomasehuang** [comment]
You can try the evaluation server here: https://eval.ai/web/challenges/challenge-page/1874.

**Comment by FelixYHH** [comment]
> You can try the evaluation server here: https://eval.ai/web/challenges/challenge-page/1874.

Thanks~
