### ISSUE TITLE
How to train on my own gpu?

### ISSUE THREAD

**Issue by StefanYz** [SysCV/bdd100k-models#7]
Hello! thank you for your work~~but i wonder if i could train these models on my own gpu? i wonder if there are som instructions or usages? plz ,thank u!

**Comment by thomasehuang** [comment]
You can follow the training instructions in [MMSegmentation](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/train.md), [MMDetection](https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md#train-predefined-models-on-standard-datasets), or [MMClassification](https://github.com/open-mmlab/mmclassification/blob/master/docs/getting_started.md#train-a-model) to train the models yourself. We provide the dataset file and config files, so you should be able to reproduce our results.
